### ISSUE TITLE
No results/GenServer terminating (killed)

### ISSUE THREAD

**Issue by jayay** [dnlserrano/exavier#22]
Hi! Whenever I run `MIX_ENV=test mix exavier.test`, this is the output:

```
..21:47:16.995 [error] GenServer #PID<0.811.0> terminating
** (stop) killed
Last message: {:EXIT, #PID<0.667.0>, :killed}
21:47:16.995 [error] GenServer #PID<0.827.0> terminating
** (stop) killed
Last message: {:EXIT, #PID<0.664.0>, :killed}
21:47:16.995 [error] GenServer Exavier.Server terminating
** (stop) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir 1.11.3) lib/task/supervised.ex:304: Task.Supervised.stream_reduce/7
    (elixir 1.11.3) lib/enum.ex:3473: Enum.reverse/1
    (elixir 1.11.3) lib/enum.ex:3066: Enum.to_list/1
    (exavier 0.3.0) lib/exavier/server.ex:59: Exavier.Server.handle_call/3
    (stdlib 3.14.2) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14.2) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.95.0>): :xmen
** (EXIT from #PID<0.95.0>) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
```

Can this be linked to #1?

This is my Erlang/Elixir info:

```
$ elixir --version
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

Thank you!

**Comment by dnlserrano** [comment]
Hey @jayay thanks for your interest in `exavier`. Maybe it's related to #1, not sure at this point. 

1. If you try to run it with `EXAVIER_DEBUG=1` does it hang forever or does it eventually finish?
2. Do you have perfect correspondence between your files and test file names? If not, consider using [`:test_files_to_modules`](https://github.com/dnlserrano/exavier#options).
3. Does [this ElixirForum thread](https://elixirforum.com/t/exavier-mutation-testing-library-for-elixir/24157/14) help in any way?
4. Is the code you're using `exavier` on publicly available so I can try and replicate on my end?

**Comment by jayay** [comment]
Hi and thank you for your answer.

I've set up `:test_files_to_modules`, but it still didn't work. It eventually finished with the `EXAVIER_DEBUG=1` environment variable set, so thank you for the hint.

The code is not public right now. Would you be okay with providing me an email address to send the code to the traditional way? 

What's the deal with the `EXAVIER_DEBUG=1` variable? Is there any chance its behavior can be made the default?

**Comment by dnlserrano** [comment]
> It eventually finished with the EXAVIER_DEBUG=1 environment variable set

Nice! At least we know it _does_ [blend](https://www.youtube.com/channel/UCnFP0IU4gpnmcLnVzDLUtfw).

> The code is not public right now. Would you be okay with providing me an email address to send the code to the traditional way?

I'd probably only be able to get to it during the weekend. "daniel j d serrano" (collapsed) then _the Internet symbol™_ followed by "proton mail" (collapsed) and the usual dot com ending.

> What's the deal with the `EXAVIER_DEBUG=1` variable? Is there any chance its behavior can be made the default?

So, `EXAVIER_DEBUG=1` was my quick way of debugging all things that are _very slow_. For particular code bases though, "very slow" might be too broad a term. That env var basically pushes [every timeout to infinity](https://github.com/dnlserrano/exavier/blob/3d4d64ebb83b533b85c51fa6f7fdd60983afa2b4/lib/exavier.ex#L182-L191). There could possibly be a way of configuring [each timeout](https://github.com/dnlserrano/exavier/blob/3d4d64ebb83b533b85c51fa6f7fdd60983afa2b4/lib/exavier.ex#L6-L11)? Could be a nice first MR. 😛  I'm guessing one of those will be slower than the defaults for you: mutating a single module, the whole code base or generating the report after mutation testing is performed.

**Comment by jayay** [comment]
I've sent you an email a couple of days back, not sure if it made it through, though. 

Thank you for your time. I'd be glad to help out, I want to familiarize myself with Elixir first. I'll be back! 😎

**Comment by dnlserrano** [comment]
Yep, haven't had time to look into it yet, sorry about the delay!
